#########################
# project configuration #
#########################

# C++ project
language: cpp

dist: trusty
sudo: required
group: edge


################
# build matrix #
################

matrix:
  include:
  # Linux / GCC
  - os: linux
      compiler: gcc
      env:
        - GCC_VERSION=7
        - CC=gcc-7
        - CXX=g++-7
        - CXXFLAGS=-std=c++17
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
  # Linux / Clang
  - os: linux
    compiler: clang
    env:
      - COMPILER=clang++-5.0
      - CXXFLAGS=-std=c++1z
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
        packages: ['g++-6', 'clang-5.0', 'libc++-dev']
  - os: linux
    compiler: clang
    env:
      - COMPILER=clang++-6.0
      - CXXFLAGS=-std=c++17
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
        packages: ['g++-6', 'clang-6.0', 'libc++-dev']

################
# build script #
################

script:
  - cmake --version
  # make sure CXX is correctly set
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi

  # show OS/compiler version
  - uname -a
  - $CXX --version

  # compile and execute unit tests
  - mkdir -p build && cd build
  - cmake .. ${CMAKE_OPTIONS} && cmake --build . --config Release
  - ctest -C Release -V -j
  - cd ..
