#########################
# project configuration #
#########################

# C++ project
language: cpp
script: cmake

################
# build matrix #
################

matrix:
  include:
    - env: CLANG_VERSION=5.0 BUILD_TYPE=Release CPP=1z LIBCXX=On
      os: linux
      addons: *clang5

    - env: GCC_VERSION=6 BUILD_TYPE=Debug CPP=1z HEADERS=On
      os: linux
      addons: *gcc6

    - env: GCC_VERSION=6 BUILD_TYPE=Release CPP=1z
      os: linux
      addons: *gcc6

################
# build script #
################

script:
  - cmake --version
  # make sure CXX is correctly set
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi

  # show OS/compiler version
  - uname -a
  - $CXX --version

  # compile and execute unit tests
  - mkdir -p build && cd build
  - cmake .. ${CMAKE_OPTIONS} && cmake --build . --config Release
  - ctest -C Release -V -j
  - cd ..
